<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>VWeatherStationGTA</AssemblyName>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ScriptHookVDotNet3" Version="3.6.0" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
